version: "3.9"

services:
    nginx:
        image: nginx:1.23.3-alpine
        volumes:
          - ./:/var/www
          - ./docker/nginx/conf.d:/etc/nginx/conf.d
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        depends_on:
            - app
        container_name: notes_nginx

    app:
        build:
            args:
                user: user
                uid: 1000
            context: .
            dockerfile: ./docker/app/Dockerfile
        volumes:
            - ./:/var/www
            - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
        container_name: notes_app

    db:
        image: mysql:5.7.22
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: notes
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/data:/var/lib/mysql/
        container_name: db
